Alias /pdf /pdf
<Directory /pdf>
    Require all granted
    Options -Indexes -ExecCGI
    AllowOverride None
    <FilesMatch "\.pdf$">
        ForceType application/pdf
        Header set X-Content-Type-Options "nosniff"
    </FilesMatch>
</Directory>
